datatypes:
    'track_uri': 'object'
    'artist_uri': 'object'
    'album_uri': 'object'
    'danceability': 'float16'
    'energy': 'float16'
    'key': 'float16'
    'loudness': 'float16'
    'mode': 'float16'
    'speechiness': 'float16' 
    'acousticness': 'float16'
    'instrumentalness': 'float16'
    'liveness': 'float16'
    'valence': 'float16' 
    'tempo': 'float16'
    'duration_ms': 'float32'
    'time_signature': 'float16'
    'Track_release_date': 'int8' 
    'Track_pop': 'int8' 
    'Artist_pop': 'int8'
    'Artist_genres': 'object'
column_names:
    - 'track_uri' 
    - 'artist_uri' 
    - 'album_uri'
    - 'danceability' 
    - 'energy' 
    - 'key'
    - 'loudness' 
    - 'mode'
    - 'speechiness' 
    - 'acousticness'
    - 'instrumentalness'
    - 'liveness' 
    - 'valence' 
    - 'tempo'
    - 'duration_ms'
    - 'time_signature'
    - 'Track_release_date' 
    - 'Track_pop' 
    - 'Artist_pop'
    - 'Artist_genres'
